### ISSUE TITLE
docker-compose run or build failes with below error:

### ISSUE THREAD

**Issue by gbspop2** [MUnique/OpenMU#184]
[root@rhel-base OpenMU]# docker logs 1a35b94e755a
[ERROR] 2020-04-21 09:55:15,058 [Npgsql.NpgsqlConnector] [(null)] - Breaking connector
Unhandled exception. Npgsql.NpgsqlException (0x80004005): Exception while connecting
 ---> System.Net.Sockets.SocketException (113): No route to host
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnection.Open()
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetAppliedMigrations()
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetAppliedMigrations(DatabaseFacade databaseFacade)
   at MUnique.OpenMU.Persistence.EntityFramework.PersistenceContextProvider.DatabaseExists() in /app/src/Persistence/EntityFramework/PersistenceContextProvider.cs:line 69
   at MUnique.OpenMU.Startup.Program.PrepareRepositoryManager(Boolean reinit, Boolean autoupdate) in /app/src/Startup/Program.cs:line 215
   at MUnique.OpenMU.Startup.Program..ctor(String[] args) in /app/src/Startup/Program.cs:line 56
   at MUnique.OpenMU.Startup.Program.Main(String[] args) in /app/src/Startup/Program.cs:line 160

**Comment by gbspop2** [comment]
Hi guys,

hope one of you can help me with the issue above.

Thank you

**Comment by sven-n** [comment]
Hi, we had a similar issue before: #144 

I have no deep docker(-compose) knowledge so I can’t really help with details. All I can see is, that application is unable to connect to the database :(

**Comment by gbspop2** [comment]
Hi Sven, odd thing is, that running the same container and command on a windows based docker works pretty much ok. Has an uptime of 29 hours.

**Comment by sven-n** [comment]
IMHO, then the chance is high that something is wrong on the Linux host system.

**Comment by gbspop2** [comment]
there is indeed. It`s a fresh install of Rhel8. I`ll try it on Rhel7 as well. Thanks

**Comment by gbspop2** [comment]
any idea where do I find the ClientExeSerial	so I can configure the client?

**Comment by sven-n** [comment]
The serial is: k1Pk2jcET48mxL3b (hex: 6B 31 50 6B 32 6A 63 45 54 34 38 6D 78 4C 33 62)

You can find it on the admin panel, if you click on Servers -> Connect Server (Season 6 Episode 3 English) -> Link to client 'Season 6 Episode 3 GMO Client'

**Comment by gbspop2** [comment]
got it.

seems that beside this and edit main.exe with hexeditor, there is something else to be done to start a client. any idea why my client doesn`t show the server?

**Comment by sven-n** [comment]
Depends on your client and the environment.
How do you start the main.exe? To which IP and Port do you connect?

**Comment by gbspop2** [comment]
I`m using a season 6 ep3 client, but I can only guess that it`s not ok.

I`m trying to configure it for local network only, so the ip address of my pc is 192.168.1.210 and I have changed it with hexeditor in main.exe in two places.

Is there a client, known working, which I can download? Or maybe a launcher?'

Thanks in advance

**Comment by sven-n** [comment]
This project contains a launcher which works pretty well with the season 6 ep3 gmo client.
Here is the source: https://github.com/MUnique/OpenMU/tree/master/src/ClientLauncher

**Comment by gbspop2** [comment]
yes, i`ve seen it, but unfortunately I don`t know how to use it...

**Comment by sven-n** [comment]
[ClientLauncher.zip](https://github.com/MUnique/OpenMU/files/4524657/ClientLauncher.zip)
I uploaded a compiled launcher for you :)

**Comment by gbspop2** [comment]
this actualy works, thanks a ton, you are awesome

**Comment by gbspop2** [comment]
any idea how can I link a MuEditor with the postgres database?

**Comment by sven-n** [comment]
> any idea how can I link a MuEditor with the postgres database?

impossible, because database schemas are totally different 😨

**Comment by gbspop2** [comment]
so, the only way to add items, or edit a character is by the admin panel?

**Comment by sven-n** [comment]
Well, you could directly edit the stuff on the database with some SQL, too ;-)

I have ideas for some better editors, but at the moment I'm focusing on implementing missing game features.

**Comment by gbspop2** [comment]
I got it, you are pushing me to the limits, thanks, that`s for the best :)

I`ll let you know if something I do works :)

**Comment by gbspop2** [comment]
any idea why I`m getting "An error has occurred. This application may no longer respond until reloaded. Reload" when I`m editing my character on the admin page?

**Comment by sven-n** [comment]
i have no idea. What exactly have you done to get the error?

I have to warn you about at least one more thing... please don’t create characters over the admin panel. The created characters will not work correctly, because some data is not correctly initialized. Better create them in game and edit them afterwards.

**Comment by gbspop2** [comment]
I have created two charactes in game, them exit game, then try to edit and get the error.

**Comment by sven-n** [comment]
What do you mean with "try to edit" exactly?

**Comment by gbspop2** [comment]
click accounts, all ok
click my account, all ok
scroll down to my characters, all ok
click edit and get the error

**Comment by sven-n** [comment]
It works for me, but I run it on Windows and with a debugger attached :/

Do you have any errors in the console or the logs?

**Comment by gbspop2** [comment]
should I use any other command than " docker-compose up -d --build" ?

this is how I started the servers.

docker logs show all ok

**Comment by sven-n** [comment]
I think that's fine.
I see, we'll need to invest more time into the configurability of the logging when it runs in docker :-(

I'll try to improve the error handling in the edit page, but I'll have no time for that until (at least) tomorrow.

**Comment by gbspop2** [comment]
no worries, I`m trying to build a website meanwhile.

**Comment by gbspop2** [comment]
any idea where do I edit the experience level?

**Comment by sven-n** [comment]
Do you mean the experience rate? Currently, it's only editable for each character in their attributes.
I want to add a global setting for that soon.

**Comment by sven-n** [comment]
I added settings for it in the admin panel:
  * At the GameConfiguration
  * For each Game Server individually

Both values are multiplied. For example, when you set 100 at both places for all servers, you'll end up with 10000x experience rate. So, it makes sense to keep the per-server setting low or at 1.

**Comment by gbspop2** [comment]
![image](https://user-images.githubusercontent.com/44093095/80213726-47df4700-8642-11ea-9706-c6ce457be120.png)

here?

**Comment by sven-n** [comment]
Nope, that’s the definition of the attribute itself. In the character edit page there is a list of stat attributes with an assigned value to this attribute. You’d need to edit that.

**Comment by gbspop2** [comment]
I have found it, but still cannot get rid of the below error:

![image](https://user-images.githubusercontent.com/44093095/80214811-1ebfb600-8644-11ea-8793-e4dc87a3dc7a.png)

**Comment by sven-n** [comment]
That’s strange :-/
I have pushed some changed today which should log and handle such errors. I recommend reinstalling with the newest docker image ;-)
Then experience rates can be set easier as well, like written above.

**Comment by tabilzad** [comment]
Also experiencing the same "This application may no longer respond until reloaded" when running in docker. The plugins page had the same behavior but seems to have been fixed with the most recent release. But still getting these same error when trying to "create" items and edit things in general.

**Comment by sven-n** [comment]
Okay, do you know if it makes a difference running docker on a linux or windows host?
I’ll try to reproduce and fix these issues.

**Comment by tabilzad** [comment]
Haven't tried on windows host yet, just linux so far. Getting a bunch of 404s when fetching blazor resources like blazored-typeahead.js etc. Also console shows promise exceptions in blazor.server.js:15

**Comment by sven-n** [comment]
As far as I know, the 404s happen when the application isn’t running from the correct working directory (where the exe is located).

**Comment by tabilzad** [comment]
You are right, i wasn't mapping any working directory at all for the docker container. Now I am mapping my host directory to /app. and so far it cant find .NET sdk when building the container. I assume my host /app directory shouldn't be empty...

**Comment by tabilzad** [comment]
yeah just looked at your Dockerfile. seems like it needs to copy things from mcr.microsoft.com/dotnet/core/aspnet

**Comment by sven-n** [comment]
I don't see a reason for the 404s :-(
The app dir contains every required dll, also Blazored.Typeahead.dll, for example. However, the StaticWebAssets of these dlls are somehow not available.

May be related: https://github.com/dotnet/aspnetcore/issues/16518

**Comment by tabilzad** [comment]
Thanks will take a look. I'm also getting System.IO.PathTooLongException which results in "Couldn't register plugin type MUnique.OpenMU.Persistence.Initialization.PlugIns.**" but i guess thats unrelated to 404s.

**Comment by sven-n** [comment]
yes, I pushed a fix for the PathTooLongException. I think it’s unrelated, too.

I did some research and found this issue: https://github.com/dotnet/aspnetcore/issues/19292

It may be possible that the Dockerfile is wrong. I’ll change it, so that it will do a dotnet build to app/ and a dotnet publish —no-build to app/publish.

**Comment by tabilzad** [comment]
yep, thats what i've been researching too. Looks like `dotnet publish` doesnt include some of the static resources for some reason. The path exceptions are now gone, thanks!

**Comment by sven-n** [comment]
I tried it, but it didn't solve the issue.
The Dockerfile:
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build

# Requirements for the typescript compiler
RUN apt-get update
RUN apt-get install npm -y
RUN npm i -g typescript

COPY src/ ./app/src

WORKDIR app

RUN dotnet build src/Startup/MUnique.OpenMU.Startup.csproj -c Release -p:ci=true

RUN dotnet publish src/Startup/MUnique.OpenMU.Startup.csproj -o out -c Release --no-build

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime

EXPOSE 1234
EXPOSE 55901
EXPOSE 55902
EXPOSE 55903
EXPOSE 44405
EXPOSE 55980

WORKDIR /app
COPY --from=build /app/out ./
ENTRYPOINT ["dotnet", "MUnique.OpenMU.Startup.dll", "-autostart"]

```

**Comment by tabilzad** [comment]
[https://forums.asp.net/t/2083717.aspx?Problem+with+static+files+ASP+NET+5+Docker](url)
[https://stackoverflow.com/questions/60379723/static-files-in-wwwroot-not-contained-in-docker-image](url)
[https://stackoverflow.com/questions/52405427/asp-net-core-2-0-static-files-not-found-error](url)
[https://stackoverflow.com/questions/54033317/how-to-get-docker-to-include-wwwroot-static-content-aspnet-core](url)
Seems like there can be a bunch of issues. Some people are saying to rename subfolders and files to lowercase, some to manually COPY the missing resources to wwwroot in the container.

**Comment by sven-n** [comment]
I got it working :)
The missing step was publishing the AdminPanel project, not the Startup :)

**Comment by tabilzad** [comment]
ahh nice!
